// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/ru/sberbank/sbervalidator/service/proto/ValidatorService.proto

// Protobuf Java Version: 3.25.1
package ru.sberbank.sbervalidator.grpc;

public interface ResultOfValidationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultOfValidation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  int getResultOfValidationCount();
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  boolean containsResultOfValidation(
      boolean key);
  /**
   * Use {@link #getResultOfValidationMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Boolean, java.lang.String>
  getResultOfValidation();
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  java.util.Map<java.lang.Boolean, java.lang.String>
  getResultOfValidationMap();
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  /* nullable */
java.lang.String getResultOfValidationOrDefault(
      boolean key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  java.lang.String getResultOfValidationOrThrow(
      boolean key);
}
