// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/ru/sberbank/sbervalidator/service/proto/ValidatorService.proto

// Protobuf Java Version: 3.25.1
package ru.sberbank.sbervalidator.grpc;

/**
 * Protobuf type {@code ResultOfValidation}
 */
public final class ResultOfValidation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ResultOfValidation)
    ResultOfValidationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResultOfValidation.newBuilder() to construct.
  private ResultOfValidation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResultOfValidation() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResultOfValidation();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ValidatorServiceProto.internal_static_ResultOfValidation_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetResultOfValidation();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ValidatorServiceProto.internal_static_ResultOfValidation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResultOfValidation.class, ResultOfValidation.Builder.class);
  }

  public static final int RESULTOFVALIDATION_FIELD_NUMBER = 1;
  private static final class ResultOfValidationDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Boolean, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Boolean, java.lang.String>newDefaultInstance(
                ValidatorServiceProto.internal_static_ResultOfValidation_ResultOfValidationEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.BOOL,
                false,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Boolean, java.lang.String> resultOfValidation_;
  private com.google.protobuf.MapField<java.lang.Boolean, java.lang.String>
  internalGetResultOfValidation() {
    if (resultOfValidation_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ResultOfValidationDefaultEntryHolder.defaultEntry);
    }
    return resultOfValidation_;
  }
  public int getResultOfValidationCount() {
    return internalGetResultOfValidation().getMap().size();
  }
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  @java.lang.Override
  public boolean containsResultOfValidation(
      boolean key) {

    return internalGetResultOfValidation().getMap().containsKey(key);
  }
  /**
   * Use {@link #getResultOfValidationMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Boolean, java.lang.String> getResultOfValidation() {
    return getResultOfValidationMap();
  }
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Boolean, java.lang.String> getResultOfValidationMap() {
    return internalGetResultOfValidation().getMap();
  }
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getResultOfValidationOrDefault(
      boolean key,
      /* nullable */
java.lang.String defaultValue) {

    java.util.Map<java.lang.Boolean, java.lang.String> map =
        internalGetResultOfValidation().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getResultOfValidationOrThrow(
      boolean key) {

    java.util.Map<java.lang.Boolean, java.lang.String> map =
        internalGetResultOfValidation().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeBooleanMapTo(
        output,
        internalGetResultOfValidation(),
        ResultOfValidationDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Boolean, java.lang.String> entry
         : internalGetResultOfValidation().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Boolean, java.lang.String>
      resultOfValidation__ = ResultOfValidationDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, resultOfValidation__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ResultOfValidation)) {
      return super.equals(obj);
    }
    ResultOfValidation other = (ResultOfValidation) obj;

    if (!internalGetResultOfValidation().equals(
        other.internalGetResultOfValidation())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetResultOfValidation().getMap().isEmpty()) {
      hash = (37 * hash) + RESULTOFVALIDATION_FIELD_NUMBER;
      hash = (53 * hash) + internalGetResultOfValidation().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResultOfValidation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResultOfValidation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResultOfValidation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResultOfValidation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResultOfValidation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResultOfValidation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResultOfValidation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResultOfValidation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ResultOfValidation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ResultOfValidation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResultOfValidation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResultOfValidation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ResultOfValidation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ResultOfValidation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ResultOfValidation)
          ResultOfValidationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidatorServiceProto.internal_static_ResultOfValidation_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetResultOfValidation();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableResultOfValidation();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidatorServiceProto.internal_static_ResultOfValidation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResultOfValidation.class, ResultOfValidation.Builder.class);
    }

    // Construct using ru.sberbank.sbervalidator.service.grpc.ResultOfValidation.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableResultOfValidation().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ValidatorServiceProto.internal_static_ResultOfValidation_descriptor;
    }

    @java.lang.Override
    public ResultOfValidation getDefaultInstanceForType() {
      return ResultOfValidation.getDefaultInstance();
    }

    @java.lang.Override
    public ResultOfValidation build() {
      ResultOfValidation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ResultOfValidation buildPartial() {
      ResultOfValidation result = new ResultOfValidation(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ResultOfValidation result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resultOfValidation_ = internalGetResultOfValidation();
        result.resultOfValidation_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResultOfValidation) {
        return mergeFrom((ResultOfValidation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResultOfValidation other) {
      if (other == ResultOfValidation.getDefaultInstance()) return this;
      internalGetMutableResultOfValidation().mergeFrom(
          other.internalGetResultOfValidation());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.Boolean, java.lang.String>
              resultOfValidation__ = input.readMessage(
                  ResultOfValidationDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableResultOfValidation().getMutableMap().put(
                  resultOfValidation__.getKey(), resultOfValidation__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Boolean, java.lang.String> resultOfValidation_;
    private com.google.protobuf.MapField<java.lang.Boolean, java.lang.String>
        internalGetResultOfValidation() {
      if (resultOfValidation_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResultOfValidationDefaultEntryHolder.defaultEntry);
      }
      return resultOfValidation_;
    }
    private com.google.protobuf.MapField<java.lang.Boolean, java.lang.String>
        internalGetMutableResultOfValidation() {
      if (resultOfValidation_ == null) {
        resultOfValidation_ = com.google.protobuf.MapField.newMapField(
            ResultOfValidationDefaultEntryHolder.defaultEntry);
      }
      if (!resultOfValidation_.isMutable()) {
        resultOfValidation_ = resultOfValidation_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return resultOfValidation_;
    }
    public int getResultOfValidationCount() {
      return internalGetResultOfValidation().getMap().size();
    }
    /**
     * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
     */
    @java.lang.Override
    public boolean containsResultOfValidation(
        boolean key) {

      return internalGetResultOfValidation().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResultOfValidationMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Boolean, java.lang.String> getResultOfValidation() {
      return getResultOfValidationMap();
    }
    /**
     * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Boolean, java.lang.String> getResultOfValidationMap() {
      return internalGetResultOfValidation().getMap();
    }
    /**
     * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getResultOfValidationOrDefault(
        boolean key,
        /* nullable */
java.lang.String defaultValue) {

      java.util.Map<java.lang.Boolean, java.lang.String> map =
          internalGetResultOfValidation().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getResultOfValidationOrThrow(
        boolean key) {

      java.util.Map<java.lang.Boolean, java.lang.String> map =
          internalGetResultOfValidation().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearResultOfValidation() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableResultOfValidation().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
     */
    public Builder removeResultOfValidation(
        boolean key) {

      internalGetMutableResultOfValidation().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Boolean, java.lang.String>
        getMutableResultOfValidation() {
      bitField0_ |= 0x00000001;
      return internalGetMutableResultOfValidation().getMutableMap();
    }
    /**
     * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
     */
    public Builder putResultOfValidation(
        boolean key,
        java.lang.String value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableResultOfValidation().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;bool, string&gt; resultOfValidation = 1;</code>
     */
    public Builder putAllResultOfValidation(
        java.util.Map<java.lang.Boolean, java.lang.String> values) {
      internalGetMutableResultOfValidation().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ResultOfValidation)
  }

  // @@protoc_insertion_point(class_scope:ResultOfValidation)
  private static final ResultOfValidation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResultOfValidation();
  }

  public static ResultOfValidation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultOfValidation>
      PARSER = new com.google.protobuf.AbstractParser<ResultOfValidation>() {
    @java.lang.Override
    public ResultOfValidation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResultOfValidation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResultOfValidation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ResultOfValidation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

