// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/ru/sberbank/sbervalidator/service/proto/ValidatorService.proto

// Protobuf Java Version: 3.25.1
package ru.sberbank.sbervalidator.grpc;

public interface ValidatorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValidatorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  int getValidationResultsCount();
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  boolean containsValidationResults(
      java.lang.String key);
  /**
   * Use {@link #getValidationResultsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, ResultOfValidation>
  getValidationResults();
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  java.util.Map<java.lang.String, ResultOfValidation>
  getValidationResultsMap();
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  /* nullable */
ResultOfValidation getValidationResultsOrDefault(
      java.lang.String key,
      /* nullable */
ResultOfValidation defaultValue);
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  ResultOfValidation getValidationResultsOrThrow(
      java.lang.String key);
}
