// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/ru/sberbank/sbervalidator/service/proto/ValidatorService.proto

// Protobuf Java Version: 3.25.1
package ru.sberbank.sbervalidator.grpc;

/**
 * Protobuf type {@code ValidatorResponse}
 */
public final class ValidatorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ValidatorResponse)
    ValidatorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidatorResponse.newBuilder() to construct.
  private ValidatorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidatorResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValidatorResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ValidatorServiceProto.internal_static_ValidatorResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetValidationResults();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ValidatorServiceProto.internal_static_ValidatorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ValidatorResponse.class, ValidatorResponse.Builder.class);
  }

  public static final int VALIDATIONRESULTS_FIELD_NUMBER = 1;
  private static final class ValidationResultsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, ResultOfValidation> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, ResultOfValidation>newDefaultInstance(
                ValidatorServiceProto.internal_static_ValidatorResponse_ValidationResultsEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                ResultOfValidation.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, ResultOfValidation> validationResults_;
  private com.google.protobuf.MapField<java.lang.String, ResultOfValidation>
  internalGetValidationResults() {
    if (validationResults_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValidationResultsDefaultEntryHolder.defaultEntry);
    }
    return validationResults_;
  }
  public int getValidationResultsCount() {
    return internalGetValidationResults().getMap().size();
  }
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  @java.lang.Override
  public boolean containsValidationResults(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetValidationResults().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValidationResultsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, ResultOfValidation> getValidationResults() {
    return getValidationResultsMap();
  }
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, ResultOfValidation> getValidationResultsMap() {
    return internalGetValidationResults().getMap();
  }
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
  ResultOfValidation getValidationResultsOrDefault(
      java.lang.String key,
      /* nullable */
ResultOfValidation defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, ResultOfValidation> map =
        internalGetValidationResults().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
   */
  @java.lang.Override
  public ResultOfValidation getValidationResultsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, ResultOfValidation> map =
        internalGetValidationResults().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetValidationResults(),
        ValidationResultsDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, ResultOfValidation> entry
         : internalGetValidationResults().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, ResultOfValidation>
      validationResults__ = ValidationResultsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, validationResults__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ValidatorResponse)) {
      return super.equals(obj);
    }
    ValidatorResponse other = (ValidatorResponse) obj;

    if (!internalGetValidationResults().equals(
        other.internalGetValidationResults())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetValidationResults().getMap().isEmpty()) {
      hash = (37 * hash) + VALIDATIONRESULTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetValidationResults().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ValidatorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidatorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidatorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidatorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidatorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidatorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidatorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValidatorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ValidatorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ValidatorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ValidatorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValidatorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ValidatorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ValidatorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ValidatorResponse)
          ValidatorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidatorServiceProto.internal_static_ValidatorResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetValidationResults();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableValidationResults();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidatorServiceProto.internal_static_ValidatorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ValidatorResponse.class, ValidatorResponse.Builder.class);
    }

    // Construct using ru.sberbank.sbervalidator.service.grpc.ValidatorResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableValidationResults().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ValidatorServiceProto.internal_static_ValidatorResponse_descriptor;
    }

    @java.lang.Override
    public ValidatorResponse getDefaultInstanceForType() {
      return ValidatorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ValidatorResponse build() {
      ValidatorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ValidatorResponse buildPartial() {
      ValidatorResponse result = new ValidatorResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ValidatorResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.validationResults_ = internalGetValidationResults().build(ValidationResultsDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ValidatorResponse) {
        return mergeFrom((ValidatorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ValidatorResponse other) {
      if (other == ValidatorResponse.getDefaultInstance()) return this;
      internalGetMutableValidationResults().mergeFrom(
          other.internalGetValidationResults());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, ResultOfValidation>
              validationResults__ = input.readMessage(
                  ValidationResultsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableValidationResults().ensureBuilderMap().put(
                  validationResults__.getKey(), validationResults__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class ValidationResultsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, ResultOfValidationOrBuilder, ResultOfValidation> {
      @java.lang.Override
      public ResultOfValidation build(ResultOfValidationOrBuilder val) {
        if (val instanceof ResultOfValidation) { return (ResultOfValidation) val; }
        return ((ResultOfValidation.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, ResultOfValidation> defaultEntry() {
        return ValidationResultsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ValidationResultsConverter validationResultsConverter = new ValidationResultsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, ResultOfValidationOrBuilder, ResultOfValidation, ResultOfValidation.Builder> validationResults_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, ResultOfValidationOrBuilder, ResultOfValidation, ResultOfValidation.Builder>
        internalGetValidationResults() {
      if (validationResults_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(validationResultsConverter);
      }
      return validationResults_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, ResultOfValidationOrBuilder, ResultOfValidation, ResultOfValidation.Builder>
        internalGetMutableValidationResults() {
      if (validationResults_ == null) {
        validationResults_ = new com.google.protobuf.MapFieldBuilder<>(validationResultsConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return validationResults_;
    }
    public int getValidationResultsCount() {
      return internalGetValidationResults().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    @java.lang.Override
    public boolean containsValidationResults(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValidationResults().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getValidationResultsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, ResultOfValidation> getValidationResults() {
      return getValidationResultsMap();
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, ResultOfValidation> getValidationResultsMap() {
      return internalGetValidationResults().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
    ResultOfValidation getValidationResultsOrDefault(
        java.lang.String key,
        /* nullable */
ResultOfValidation defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, ResultOfValidationOrBuilder> map = internalGetMutableValidationResults().ensureBuilderMap();
      return map.containsKey(key) ? validationResultsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    @java.lang.Override
    public ResultOfValidation getValidationResultsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, ResultOfValidationOrBuilder> map = internalGetMutableValidationResults().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return validationResultsConverter.build(map.get(key));
    }
    public Builder clearValidationResults() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableValidationResults().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    public Builder removeValidationResults(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableValidationResults().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, ResultOfValidation>
        getMutableValidationResults() {
      bitField0_ |= 0x00000001;
      return internalGetMutableValidationResults().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    public Builder putValidationResults(
        java.lang.String key,
        ResultOfValidation value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableValidationResults().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    public Builder putAllValidationResults(
        java.util.Map<java.lang.String, ResultOfValidation> values) {
      for (java.util.Map.Entry<java.lang.String, ResultOfValidation> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableValidationResults().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .ResultOfValidation&gt; validationResults = 1;</code>
     */
    public ResultOfValidation.Builder putValidationResultsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, ResultOfValidationOrBuilder> builderMap = internalGetMutableValidationResults().ensureBuilderMap();
      ResultOfValidationOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = ResultOfValidation.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof ResultOfValidation) {
        entry = ((ResultOfValidation) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (ResultOfValidation.Builder) entry;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ValidatorResponse)
  }

  // @@protoc_insertion_point(class_scope:ValidatorResponse)
  private static final ValidatorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ValidatorResponse();
  }

  public static ValidatorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidatorResponse>
      PARSER = new com.google.protobuf.AbstractParser<ValidatorResponse>() {
    @java.lang.Override
    public ValidatorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValidatorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidatorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ValidatorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

