// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/ru/sberbank/sbervalidator/service/proto/ValidatorService.proto

// Protobuf Java Version: 3.25.1
package ru.sberbank.sbervalidator.grpc;

/**
 * Protobuf type {@code ValidatorRequest}
 */
public final class ValidatorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ValidatorRequest)
    ValidatorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidatorRequest.newBuilder() to construct.
  private ValidatorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidatorRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValidatorRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ValidatorServiceProto.internal_static_ValidatorRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetDocumentContents();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ValidatorServiceProto.internal_static_ValidatorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ValidatorRequest.class, ValidatorRequest.Builder.class);
  }

  public static final int DOCUMENTCONTENTS_FIELD_NUMBER = 1;
  private static final class DocumentContentsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                ValidatorServiceProto.internal_static_ValidatorRequest_DocumentContentsEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> documentContents_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetDocumentContents() {
    if (documentContents_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DocumentContentsDefaultEntryHolder.defaultEntry);
    }
    return documentContents_;
  }
  public int getDocumentContentsCount() {
    return internalGetDocumentContents().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; documentContents = 1;</code>
   */
  @java.lang.Override
  public boolean containsDocumentContents(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetDocumentContents().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDocumentContentsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getDocumentContents() {
    return getDocumentContentsMap();
  }
  /**
   * <code>map&lt;string, string&gt; documentContents = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getDocumentContentsMap() {
    return internalGetDocumentContents().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; documentContents = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getDocumentContentsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDocumentContents().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; documentContents = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getDocumentContentsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDocumentContents().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetDocumentContents(),
        DocumentContentsDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetDocumentContents().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      documentContents__ = DocumentContentsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, documentContents__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ValidatorRequest)) {
      return super.equals(obj);
    }
    ValidatorRequest other = (ValidatorRequest) obj;

    if (!internalGetDocumentContents().equals(
        other.internalGetDocumentContents())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetDocumentContents().getMap().isEmpty()) {
      hash = (37 * hash) + DOCUMENTCONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetDocumentContents().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ValidatorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidatorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidatorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidatorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidatorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidatorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidatorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValidatorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ValidatorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ValidatorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ValidatorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValidatorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ValidatorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ValidatorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ValidatorRequest)
          ValidatorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidatorServiceProto.internal_static_ValidatorRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetDocumentContents();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableDocumentContents();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidatorServiceProto.internal_static_ValidatorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ValidatorRequest.class, ValidatorRequest.Builder.class);
    }

    // Construct using ru.sberbank.sbervalidator.service.grpc.ValidatorRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableDocumentContents().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ValidatorServiceProto.internal_static_ValidatorRequest_descriptor;
    }

    @java.lang.Override
    public ValidatorRequest getDefaultInstanceForType() {
      return ValidatorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ValidatorRequest build() {
      ValidatorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ValidatorRequest buildPartial() {
      ValidatorRequest result = new ValidatorRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ValidatorRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.documentContents_ = internalGetDocumentContents();
        result.documentContents_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ValidatorRequest) {
        return mergeFrom((ValidatorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ValidatorRequest other) {
      if (other == ValidatorRequest.getDefaultInstance()) return this;
      internalGetMutableDocumentContents().mergeFrom(
          other.internalGetDocumentContents());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              documentContents__ = input.readMessage(
                  DocumentContentsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableDocumentContents().getMutableMap().put(
                  documentContents__.getKey(), documentContents__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> documentContents_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetDocumentContents() {
      if (documentContents_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DocumentContentsDefaultEntryHolder.defaultEntry);
      }
      return documentContents_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableDocumentContents() {
      if (documentContents_ == null) {
        documentContents_ = com.google.protobuf.MapField.newMapField(
            DocumentContentsDefaultEntryHolder.defaultEntry);
      }
      if (!documentContents_.isMutable()) {
        documentContents_ = documentContents_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return documentContents_;
    }
    public int getDocumentContentsCount() {
      return internalGetDocumentContents().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; documentContents = 1;</code>
     */
    @java.lang.Override
    public boolean containsDocumentContents(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetDocumentContents().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDocumentContentsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDocumentContents() {
      return getDocumentContentsMap();
    }
    /**
     * <code>map&lt;string, string&gt; documentContents = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getDocumentContentsMap() {
      return internalGetDocumentContents().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; documentContents = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getDocumentContentsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDocumentContents().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; documentContents = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getDocumentContentsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDocumentContents().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearDocumentContents() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableDocumentContents().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; documentContents = 1;</code>
     */
    public Builder removeDocumentContents(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableDocumentContents().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableDocumentContents() {
      bitField0_ |= 0x00000001;
      return internalGetMutableDocumentContents().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; documentContents = 1;</code>
     */
    public Builder putDocumentContents(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableDocumentContents().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; documentContents = 1;</code>
     */
    public Builder putAllDocumentContents(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableDocumentContents().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ValidatorRequest)
  }

  // @@protoc_insertion_point(class_scope:ValidatorRequest)
  private static final ValidatorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ValidatorRequest();
  }

  public static ValidatorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidatorRequest>
      PARSER = new com.google.protobuf.AbstractParser<ValidatorRequest>() {
    @java.lang.Override
    public ValidatorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValidatorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidatorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ValidatorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

