// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/ru/sberbank/sbervalidator/service/proto/ValidatorService.proto

// Protobuf Java Version: 3.25.1
package ru.sberbank.sbervalidator.grpc;

public final class ValidatorServiceProto {
  private ValidatorServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidatorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidatorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidatorRequest_DocumentContentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidatorRequest_DocumentContentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultOfValidation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultOfValidation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultOfValidation_ResultOfValidationEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultOfValidation_ResultOfValidationEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidatorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidatorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidatorResponse_ValidationResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidatorResponse_ValidationResultsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nLsrc/main/java/ru/sberbank/sbervalidato" +
      "r/service/proto/ValidatorService.proto\"\216" +
      "\001\n\020ValidatorRequest\022A\n\020documentContents\030" +
      "\001 \003(\0132\'.ValidatorRequest.DocumentContent" +
      "sEntry\0327\n\025DocumentContentsEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\230\001\n\022ResultOfVali" +
      "dation\022G\n\022resultOfValidation\030\001 \003(\0132+.Res" +
      "ultOfValidation.ResultOfValidationEntry\032" +
      "9\n\027ResultOfValidationEntry\022\013\n\003key\030\001 \001(\010\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"\250\001\n\021ValidatorResponse" +
      "\022D\n\021validationResults\030\001 \003(\0132).ValidatorR" +
      "esponse.ValidationResultsEntry\032M\n\026Valida" +
      "tionResultsEntry\022\013\n\003key\030\001 \001(\t\022\"\n\005value\030\002" +
      " \001(\0132\023.ResultOfValidation:\0028\0012L\n\020Validat" +
      "orService\0228\n\017ValidateRequest\022\021.Validator" +
      "Request\032\022.ValidatorResponseBA\n&ru.sberba" +
      "nk.sbervalidator.service.grpcB\025Validator" +
      "ServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ValidatorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ValidatorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidatorRequest_descriptor,
        new java.lang.String[] { "DocumentContents", });
    internal_static_ValidatorRequest_DocumentContentsEntry_descriptor =
      internal_static_ValidatorRequest_descriptor.getNestedTypes().get(0);
    internal_static_ValidatorRequest_DocumentContentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidatorRequest_DocumentContentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ResultOfValidation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResultOfValidation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultOfValidation_descriptor,
        new java.lang.String[] { "ResultOfValidation", });
    internal_static_ResultOfValidation_ResultOfValidationEntry_descriptor =
      internal_static_ResultOfValidation_descriptor.getNestedTypes().get(0);
    internal_static_ResultOfValidation_ResultOfValidationEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultOfValidation_ResultOfValidationEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ValidatorResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ValidatorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidatorResponse_descriptor,
        new java.lang.String[] { "ValidationResults", });
    internal_static_ValidatorResponse_ValidationResultsEntry_descriptor =
      internal_static_ValidatorResponse_descriptor.getNestedTypes().get(0);
    internal_static_ValidatorResponse_ValidationResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidatorResponse_ValidationResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
